# Generated by Django 3.0.8 on 2020-08-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200824_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
